### PR TITLE
Spelling fix

### PR DESCRIPTION
**Pull request by onlineth**
"appropritate" is spelled wrong, it should be spelled as "appropriate"

### CODE REVIEW

**Comment by oliversalzburg** [comment]
What's with the other changed files in that commit?

**Comment by Benjol** [comment]
@oliversalzburg, thanks for maintaining your interest in AutoReviewComments, I must confess I've been on the back seat recently...

**Comment by onlineth** [comment]
@oliversalzburg Honestly I did this twice and for some reason, it shows a differ on parts of the autoreviewcomments.user.js file; however, I see absolutely no difference

**Comment by oliversalzburg** [comment]
@onlineth It's probably different line endings. You don't have to rebuild the `dist` files for this change. We'll take care of it.

**Comment by onlineth** [comment]
ok, I'll just change the src/autoreviewcomments.user.js

**Comment by oliversalzburg** [comment]
Btw, you can just change your commit in a feature branch with `git commit --amend` and the force push that feature branch `git push -f` to update a PR.

**Comment by onlineth** [comment]
@oliversalzburg Wow, I know a dozen times that would've been helpful in the past, thanks

**Pull request closed without merging**
