### PR TITLE
Readme improvements

### PR DESCRIPTION
**Pull request by Julian-O**
Primarily fixed two important broken links. Also, some minor copy-editing.

### CODE REVIEW

**Comment by Benjol** [comment]
Hello @Julian-O , thanks for submitting it. You actually have a typo in your second commit (browswers) :)

If you're motivated, you might want to update that bit of text even more, and point directly to each of the following:
The raw scripts (which you corrected the links to)
The Mozilla add-on: https://addons.mozilla.org/en-US/firefox/addon/se-autoreviewcomments
The 'official' Chrome extension: https://chrome.google.com/webstore/detail/autoreviewcomments/bcfoamnigomkoaaiceppbbdlembpeejc?hl=fr
The Opera extension: https://addons.opera.com/fr/extensions/details/se-autoreviewcomments

**Comment by Julian-O** [comment]
Sorry for the typos. Hopefully fixed.

**Comment by Julian-O** [comment]
WIll add those links.

**Comment by Julian-O** [comment]
Done. I'm still learning github's pull requests. Do I need to issue another pull-request or do you just grab from this branch when you are happy with it?

**Comment by Benjol** [comment]
Looks good to me, and github seems to have worked out what you wanted.

**Pull request merged**
