### PR TITLE
Fix #156 - Default welcome message references incorrect variable

### LINKED ISSUE #156: Default welcome message references incorrect variable for site name
Fresh install of AutoReviewComments userscript uses the wrong site name.

> Welcome to Where Developers Learn, Share, & Build Careers! 

capture

### PR DESCRIPTION
**Pull request by samliew**
Remove dependency on format of site title

### CODE REVIEW

**Comment by oliversalzburg** [comment]
@samliew Thanks for the contribution!

**Comment by gparyani** [comment]
@oliversalzburg I find it very strange that you said in #154 that you wouldn't be reviewing pull requests, and that the script was essentially abandoned. Just one week later, you approved this. Any chance you'd be willing to reconsider your comment there?

**Comment by Benjol** [comment]
@gparyani it's a question of availability. I suspect @oliversalzburg had a bit of time, saw the pull request was low risk and just did it.

I say this because I have a similar level of engagement (both with SO and this script). Oliver has been managing it in my mostly-absence over the past years. If someone wants to step up to the plate they're quite welcome.

The thing is, since I first developed this script, both Firefox and Chrome have been continually changing their plugin/extension mechanisms, so keeping up with them has been exhausting and I gave up.

**Comment by oliversalzburg** [comment]
@gparyani #154 is an issue, #157 is a pull request. Reviewing and merging a pull request is one thing, writing new code to fulfill the wishes of random StackOverflow users is another.

I just didn't want you to get your hopes up that anyone would be happy to improve this script just because they love the community so much. I still reserve the right to randomly be friendly and helpful when I can :)

**Pull request merged**
